" Geral
set wildmenu
set viminfo=
set splitright

" Desabilita backups
set nobackup
set noswapfile
set nowritebackup

" Visual (cores, tema etc)
filetype on
filetype plugin off
syntax on
colorscheme elflord
set background=dark

set number
set ruler
set title

" Tabs e espaços
set expandtab
set nostartofline
set shiftwidth=4
set tabstop=4

" Cursor e colunas
" set cursorline
set cursorcolumn

" Vim 7.2 não suporta 'colorcolumn'
if exists('+colorcolumn')
  set colorcolumn=80
endif

highlight CursorColumn ctermbg=234
highlight ColorColumn ctermbg=234

" Indentação
" filetype plugin indent on
" set autoindent

" Busca
set ignorecase
set hlsearch
set incsearch

" Codificação
set encoding=utf-8
set fileencoding=utf-8

" Atalhos
map 0 ^

map <Tab> :tabnext<cr>
map <S-Tab> :tabprevious<cr>

" Pathogen
if filereadable(expand($HOME . "/.vim/autoload/pathogen.vim"))
    execute pathogen#infect()
endif

" Sintaxe de arquivos
au BufNewFile,BufRead Jenkinsfile set filetype=groovy
au BufNewFile,BufRead Jenkinsfile set filetype=groovy
au BufNewFile,BufRead Vagrantfile set filetype=ruby
au BufNewFile,BufRead composer.lock set filetype=json
au BufNewFile,BufRead docker-compose*.yml set filetype=yaml
au BufNewFile,BufRead kops-edit*yaml set filetype=yaml
au BufNewFile,BufRead *.kube/config set filetype=yaml
au BufNewFile,BufRead *.textile set filetype=redminewiki
au BufNewFile,BufRead *.tfstate set filetype=json
au BufNewFile,BufRead *.aws/config set filetype=cfg
au BufNewFile,BufRead *.aws/credentials set filetype=cfg

" Configurações por tipo de arquivo
autocmd Filetype ruby setlocal ts=2 sts=2 sw=2
autocmd Filetype terraform setlocal ts=2 sts=2 sw=2
autocmd Filetype yaml setlocal ts=2 sts=2 sw=2
