" Geral
set wildmenu
set viminfo=
set splitright

" Desabilita backups
set nobackup
set noswapfile
set nowritebackup

" Visual (cores, tema etc)
filetype on
filetype plugin off
syntax on
colorscheme elflord
set background=dark

set number
set ruler
set title

" Tabs e espaços
set expandtab
set nostartofline
set shiftwidth=4
set tabstop=4

" Cursor e colunas
" set cursorline
set cursorcolumn

" Vim 7.2 não suporta 'colorcolumn'
if exists('+colorcolumn')
  set colorcolumn=80
endif

highlight CursorColumn ctermbg=DarkGray
highlight ColorColumn ctermbg=DarkGray

" Indentação
" filetype plugin indent on
" set autoindent

" Busca
set ignorecase
set hlsearch
set incsearch

" Codificação
set encoding=utf-8
set fileencoding=utf-8

" Sintaxe de arquivos
au BufNewFile,BufRead Jenkinsfile set filetype=groovy

" Atalhos
map 0 ^

map <Tab> :tabnext<cr>
map <S-Tab> :tabprevious<cr>

" Pathogen
if filereadable(expand($HOME . "/.vim/autoload/pathogen.vim"))
    execute pathogen#infect()
endif
