" Geral
set wildmenu
set viminfo=

" Desabilita backups
set nobackup
set noswapfile
set nowritebackup

" Visual (cores, tema etc)
filetype on
" filetype plugin on
syntax on
colorscheme elflord
set background=dark

set number
set ruler
set title

" Tabs e espaços
set expandtab
set nostartofline
set shiftwidth=4
set tabstop=4

" Cursor e colunas
" set cursorline
set cursorcolumn
set colorcolumn=80
highlight CursorColumn ctermbg=DarkGray
highlight ColorColumn ctermbg=DarkGray

" Indentação
" filetype plugin indent on
" set autoindent

" Busca
set ignorecase
set hlsearch
set incsearch

" Codificação
set encoding=utf-8

" Atalhos
map 0 ^
